### PR TITLE
Cleanup asset heirarchy

### PR DESCRIPTION
**Pull request by mjuvekar7**
* Moved the SquashVine assets to the Vines asset folders to be more consistent with the current file heirarchy.

There seem to be inconsistencies with other plants too, including the Apple tree (whose assets for some reason are in both, "Bushes" and "Trees" folders), the pineapple (some of whose assets are in the root directories and not in any plant type directory) and the guava and pear plants.

### CODE REVIEW

**Comment by jellysnake** [comment]
So this is actually already in pull request #58, which in addition to redoing all the internal file layouts also utterly redoes all the plants as phase one of the overhaul.

**Comment by mjuvekar7** [comment]
Isn't #58 already merged? Why haven't sqaush vine and apple and the other things mentioned above been moved?

**Comment by jellysnake** [comment]
It was merged after this pull request was opened. So they have been moved around now, but they weren't when you originally created the pull request.

**Comment by mjuvekar7** [comment]
Oh alright, my bad. Sorry for this :)

**Pull request closed without merging**
