### PR TITLE
GCI TASK(JayGupta2003)(Added Guava Bush)

### PR DESCRIPTION
**Pull request by JayGupta2003**

### CODE REVIEW

**Comment by smsunarto** [comment]
Hey, @JayGupta2003. There's an un-used growth stage it seems (Mature Guava Bush), if you are not planning to use that, you can delete the block file. But if you are planning to use it, you need to add that stage in the seed prefab file.

There's also some missing texture files for:

- Guava Seed
- Guava Bush
- Mature Guava Bush
- Guava Bush Full

**Comment by Cervator** [comment]
Thanks for the review @smsunarto ! Very helpful :-)

Feel free to poke a mentor to let us know if you spot something like this, then we can send the task back for more work in case the student is looking more at the GCI site than a PR.

Appreciate it!

@JayGupta2003: Looking forward to the fixes - and please test your changes this time ... :-)

**Comment by smsunarto** [comment]
@JayGupta2003 Thanks for the update.

1. I think the bush blockTiles shouldn't look like that, since those images is going to be mirrored to 6 sides to create a block. Refer to other bushes (Eg: Testberry) for a good example.

2. You have a filed called MatureBushFull.png - You need to rename this to MatureGuavaBush since MatureBushFull already existed and will cause conflicts.

3. You should also renamed `Guava Seeds.png` to `Guavaseed.png` since it's the one that's called on line 7 of your seed prefab file `    "icon": "SimpleFarming:Guavaseed",`

**Comment by Cervator** [comment]
Thanks for reviewing again @smsunarto :-)

@JayGupta2003 let us know if you're wanting to finish this before the task claim deadline, ideally by coming on IRC. If not and you're just interested in doing this PR well then please take your time. Especially since you still don't seem to be testing your changes?

**Comment by smsunarto** [comment]
Hey @JayGupta2003. Thanks for the changes :D

I still need those blockTiles texture to be changed. It looks kinda weird in-game if you have too much transparent background for a bush. It will look like a 6 side floating fruits.

CC: @Cervator

**Comment by smsunarto** [comment]
Tested in-game, bushes are working, textures are loaded.




I'm not sure whether or not the textures are acceptable, since it's too pixelated. I hand this too you cerv.

CC: @Cervator

**Comment by Cervator** [comment]
Thanks again @smsunarto - yeah the image quality is pretty low. But it does work and it is more about the concept than high quality artwork. At some point after GCI is fully done and we have time we'll reorganize and move things around some more, including some based on quality.

@JayGupta2003: Thanks for keeping on this issue. I hope you've found GCI to be an educational experience and that you'll continue to improve. We'll be here even after GCI if you're interested in continuing without any kind of time pressure (but likely also higher quality requirements)

Closing as merged via rebase & squash in https://github.com/Terasology/SimpleFarming/commit/f55f7ff84223ee773ea285909669d7679f42ac7e

**Pull request closed without merging**
