### PR TITLE
Add support for fruit trees

### PR DESCRIPTION
**Pull request by iojw**
### Contains

This adds support for fruit trees.

For an overview for tree behaviour as well as how trees can be created with the various options available, take a look at the **Creating Trees** section under the README here which I've updated: https://github.com/iojw/SimpleFarming/tree/fruit-trees. 

This also contains javadocs for the classes that I've added where appropriate, as well as various typo and formatting fixes.

### How to Test
I've added prefabs and textures for a Peach Tree, which you can test using `give peachtreeseed` and planting it in the ground.

### Thoughts

With this, what I was aiming for was to allow as many different different types of trees to be created as possible, so I tried to include various customisation options for the prefabs, such as the sapling and fruit growth stages. I didn't want to limit trees to a certain shape, so I've added the ability the customise the way in which the leaves are formed. Although this implementation still limits it to only square shaped canopy layers, I'm not sure what would be a better way of doing this without making it too complicated. Looking at other implementations, Terasology and GrowingFlora both use a pretty complicated algorithm called L-system which I'm not entirely sure how it works.

Apart from that, there only exists one persistent entity for each tree currently, which is the base of the trunk. Destroying this would stop the growth of the fruit blocks, as well as cause the fruits to be destroyed over a period of time. While it would make sense for this to apply to the whole of the trunk, doing so would require a persistent component for each of the trunk blocks and that's why I've left those out.

Should the fruit blocks drop seeds? Given that the fruit blocks are non-persistent, I think that this might be an all or nothing thing, since it would have to be defined in the prefab.

There is an unintended interaction which I'm unsure whether it's a bug. After using `worldProvider.setBlock()` on the sapling's location to turn it into the trunk, the trunk still seems to retain the properties of the sapling, allowing me to destroy it in a single hit. Is there something I should be doing to update the trunk's properties? I've tried replacing it with air and destroying it first but both seems to turn the trunk block indestructible 😐.

I've based most of this on my own judgement so do let me know if you disagree with anything or if there's anything you would like me to change!

### CODE REVIEW

**Comment by Cervator** [comment]
Looks great and seems to work great! Nicely done :-)

Only noticed two potential outstanding issues:

* The trunk blocks were not destroyed along with the canopy - could that be added it? Very tidy process, cleaned up all the leaf blocks.
* When a dead canopy block is removed a stacktrace is thrown. Unsure if it is just a benign bit of noise or was one last bit of fruit meant to drop?

```
02:04:25.250 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
02:04:26.046 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.world.block.entity.BlockEntitySystem.commonDefaultDropsHandling(BlockEntitySystem.java:133)
	at org.terasology.world.block.entity.BlockEntitySystem.defaultDropsHandling(BlockEntitySystem.java:93)
	at org.terasology.world.block.entity.BlockEntitySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.world.block.entity.BlockEntitySystem.commonDestroyed(BlockEntitySystem.java:153)
	at org.terasology.world.block.entity.BlockEntitySystem.doDestroy(BlockEntitySystem.java:86)
	at org.terasology.world.block.entity.BlockEntitySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.simpleFarming.systems.TreeAuthoritySystem.onFruitDestroy(TreeAuthoritySystem.java:319)
	at org.terasology.simpleFarming.systems.TreeAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.delay.DelayedActionSystem.lambda$invokeDelayedOperations$91(DelayedActionSystem.java:91)
	at org.terasology.logic.delay.DelayedActionSystem$$Lambda$250/904872862.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.logic.delay.DelayedActionSystem.invokeDelayedOperations(DelayedActionSystem.java:78)
	at org.terasology.logic.delay.DelayedActionSystem.update(DelayedActionSystem.java:61)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:160)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
02:04:26.227 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
```

Nice documentation!

As for seeds I would just have the blocks give seeds when broken, while `e` clicking yields produce? Alternatively you could mix in the BlockDropGrammar to vary drops both by chance and quantity.

The sapling switching block but not characteristics may be due to its entity not changing? It may be possible to destroy the entity and replacing it with a replacement trunk entity? Or maybe something just isn't being cleaned up fully when the switch happens.

Interestingly over in Throughout the Ages there is a weird issue where the bottom trunk block (which again is a controller block) remains a sapling *until looked at* - which is probably something else, but still seems sort of similar. https://github.com/Terasology/GrowingFlora/issues/2

**Comment by Cervator** [comment]
Poking @Josharias and @xrtariq2594 in case they'd like to check this out as well, would be good with another pair of eyes or two.

**Comment by iojw** [comment]
@Cervator: Cool, I've fixed all the issues mentioned and updated the README accordingly.

I initially left the trunk blocks intentionally as I was thinking that they would still remain after a tree dies, but I've changed it such that they get destroyed immediately along with the controller.

And yup seems calling `destroy()` on the entity before setting the trunk block fixed the problem 🙂.

**Comment by Cervator** [comment]
Perfect! Great work :-)

**Pull request merged**
